name: (STAGING)

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Deploy branch to Vercel
        id: vercel_branch_deploy
        run: |
          URL=$(npx vercel --confirm -n vue-pet -t ${{ secrets.VERCEL_TOKEN }})
          echo ::set-output name=url::$URL